In [1]:
import numpy as np

arr = np.arange(1, 11)
reshaped_arr = arr.reshape(2, 5)
print(reshaped_arr)


[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [2]:
arr = np.arange(1, 21)
sliced = arr[5:16]  # from index 5 to 15
print(sliced)


[ 6  7  8  9 10 11 12 13 14 15 16]


In [3]:
import pandas as pd

fruits = pd.Series({'apples': 3, 'bananas': 2, 'oranges': 1})
fruits['pears'] = 4
print(fruits)


apples     3
bananas    2
oranges    1
pears      4
dtype: int64


In [4]:
data = {
    'name': ['Alice', 'Bob', 'Charlie', 'David', 'Eve', 'Fay', 'Grace', 'Hank', 'Ivy', 'John'],
    'age': [25, 32, 28, 40, 22, 30, 26, 38, 29, 33],
    'gender': ['F', 'M', 'M', 'M', 'F', 'F', 'F', 'M', 'F', 'M']
}
df = pd.DataFrame(data)
print(df)


      name  age gender
0    Alice   25      F
1      Bob   32      M
2  Charlie   28      M
3    David   40      M
4      Eve   22      F
5      Fay   30      F
6    Grace   26      F
7     Hank   38      M
8      Ivy   29      F
9     John   33      M


In [5]:
occupations = ['Programmer', 'Manager', 'Analyst', 'Programmer', 'Manager', 'Analyst', 'Programmer', 'Manager', 'Analyst', 'Programmer']
df['occupation'] = occupations
print(df)


      name  age gender  occupation
0    Alice   25      F  Programmer
1      Bob   32      M     Manager
2  Charlie   28      M     Analyst
3    David   40      M  Programmer
4      Eve   22      F     Manager
5      Fay   30      F     Analyst
6    Grace   26      F  Programmer
7     Hank   38      M     Manager
8      Ivy   29      F     Analyst
9     John   33      M  Programmer


In [6]:
age_30_plus = df[df['age'] >= 30]
print(age_30_plus)


    name  age gender  occupation
1    Bob   32      M     Manager
3  David   40      M  Programmer
5    Fay   30      F     Analyst
7   Hank   38      M     Manager
9   John   33      M  Programmer


In [7]:
# Save to CSV
df.to_csv('people.csv', index=False)

# Read from CSV
read_df = pd.read_csv('people.csv')
print(read_df)


      name  age gender  occupation
0    Alice   25      F  Programmer
1      Bob   32      M     Manager
2  Charlie   28      M     Analyst
3    David   40      M  Programmer
4      Eve   22      F     Manager
5      Fay   30      F     Analyst
6    Grace   26      F  Programmer
7     Hank   38      M     Manager
8      Ivy   29      F     Analyst
9     John   33      M  Programmer
